version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      kafkaBootstrapServers: host.docker.internal:9094
      kafkaHL7Topic: hl7-messages

